options:
  docker: true
clone:
  depth: full

pipelines:
  branches:
    "{feature/*,sprint*}":
      - step:
          name: "[Homolog - Build]"
          image: atlassian/pipelines-awscli:latest
          script:
            # AWS ECR Login
            - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
            - docker build -t 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:$BUILD_ID -f ./Dockerfile .

            # # Push Docker Image to AWS ECR
            - docker tag 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:$BUILD_ID 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER
            - docker push 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER

      - step:
          name: "[Homolog - Deploy]"
          image: conexia/bitbucket-pipeline:latest
          trigger: manual
          script:
            # Configure Kops Settings
            - export KOPS_STATE_STORE=$HML_KOPS_STATE_STORE
            - kops export kubecfg $HML_CLUSTER_NAME

            # Update Kubernetes Deployment Image
            - kubectl set image deployment/h-pdf-annotations-service h-pdf-annotations-service=517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER -n $HML_KUBERNETES_APP_NAMESPACE

    "{integracao}":
      - step:
          name: "[Integração - Build]"
          image: atlassian/pipelines-awscli:latest
          script:
            # AWS ECR Login
            - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
            - docker build -t 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:$BUILD_ID -f ./Dockerfile .

            # # Push Docker Image to AWS ECR
            - docker tag 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:$BUILD_ID 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER
            - docker push 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER

      - step:
          name: "[Integração - Deploy]"
          image: conexia/bitbucket-pipeline:latest
          trigger: manual
          script:
            # Configure Kops Settings
            - export KOPS_STATE_STORE=$INT_KOPS_STATE_STORE
            - kops export kubecfg $INT_CLUSTER_NAME

            # Update Kubernetes Deployment Image
            - kubectl set image deployment/int-pdf-annotations-service int-pdf-annotations-service=517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER -n $INT_KUBERNETES_APP_NAMESPACE

    "{planejamento}":
      - step:
          name: "[Planejamento] Build"
          image: atlassian/pipelines-awscli:latest
          script:
            # AWS ECR Login
            - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER

            # Push Docker Image to AWS ECR
            - docker build -t 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:$BUILD_ID --target NODE_PROD -f ./Dockerfile .
            - docker tag 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:$BUILD_ID 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER
            - docker push 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER

      - step:
          name: "[Planejamento] Deploy"
          image: conexia/bitbucket-pipeline:latest
          trigger: manual
          script:
            # Configure Kops Settings
            - export KOPS_STATE_STORE=$PLA_KOPS_STATE_STORE
            - kops export kubecfg $PLA_CLUSTER_NAME

            # Update Kubernetes Deployment Image
            - kubectl set image deployment/pla-pdf-annotations-service pla-pdf-annotations-service=517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER -n $PLA_KUBERNETES_APP_NAMESPACE

    "{develop,fix*,hotfix*}":
      - step:
          name: "[Develop- Build]"
          image: atlassian/pipelines-awscli:latest
          script:
            # AWS ECR Login
            - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
            - docker build -t 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:$BUILD_ID -f ./Dockerfile .

            # # Push Docker Image to AWS ECR
            - docker tag 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:$BUILD_ID 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER
            - docker push 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER

      - step:
          name: "[Homolog - Deploy]"
          image: conexia/bitbucket-pipeline:latest
          trigger: manual
          script:
            # Configure Kops Settings
            - export KOPS_STATE_STORE=$HML_KOPS_STATE_STORE
            - kops export kubecfg $HML_CLUSTER_NAME

            # Update Kubernetes Deployment Image
            - kubectl set image deployment/h-pdf-annotations-service h-pdf-annotations-service=517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER -n $HML_KUBERNETES_APP_NAMESPACE

      - step:
          name: "[QA - Deploy]"
          image: conexia/bitbucket-pipeline:latest
          trigger: manual
          script:
            # Configure Kops Settings
            - export KOPS_STATE_STORE=$QA_KOPS_STATE_STORE
            - kops export kubecfg $QA_CLUSTER_NAME

            # Update Kubernetes Deployment Image
            - kubectl set image deployment/qa-pdf-annotations-service qa-pdf-annotations-service=517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER -n $QA_KUBERNETES_APP_NAMESPACE

    "{master}":
      - step:
          name: "[Prod - Build]"
          image: atlassian/pipelines-awscli:latest
          script:
            # AWS ECR Login
            - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
            - docker build -t 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:$BUILD_ID -f ./Dockerfile .

            # # Push Docker Image to AWS ECR
            - docker tag 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:$BUILD_ID 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER
            - docker push 517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER

      - step:
          name: "[Prod - Deploy]"
          image: conexia/bitbucket-pipeline:latest
          trigger: manual
          script:
            # Configure Kops Settings
            - export KOPS_STATE_STORE=PRD_KOPS_STATE_STORE
            - kops export kubecfg PRD_CLUSTER_NAME

            # Update Kubernetes Deployment Image
            - kubectl set image deployment/pdf-annotations-service pdf-annotations-service=517542778447.dkr.ecr.sa-east-1.amazonaws.com/pdf-annotations-service:prod-$BITBUCKET_BUILD_NUMBER -n PRD_KUBERNETES_APP_NAMESPACE

            - pipe: atlassian/slack-notify:0.3.6
              variables:
                WEBHOOK_URL: $WEBHOOK_URL
                MESSAGE: "Deploy in Production.\n$BITBUCKET_REPO_SLUG ($BITBUCKET_PROJECT_KEY) on branch $BITBUCKET_BRANCH"